# nginx.conf

server {
             listen 80;
                server_name career-scouter.com;

                index index.html;

                location / {
                        root /var/www/example.com;
                        index index.html;
                        try_files $uri $uri/ /index.html;
                }
}
